spring.application.name: jconon

hazelcast:
  members: 127.0.0.1
  port:
    autoincrement: false
server:
  servlet:
    context-path: /jconon

ajp:
  port: 8009
  timeout: 120000

org.apache.chemistry.opencmis.binding.clientcompression: false
org.apache.chemistry.opencmis.binding.compression: true

spring.main.allow-bean-definition-overriding: true

#Tomcat
server.tomcat.basedir: ./
server.tomcat.access-log-enabled: true
server.tomcat.access-log-pattern: '%h %l %u %t "%r" %s %b %D'

shell.auth.simple.user.name: ${user.admin.username}
shell.auth.simple.user.password: ${user.admin.password}

pec:
  mail:
    hostImap: imaps.pec.aruba.it
    hostSmtp: smtps.pec.aruba.it
    url: imaps://${pec.mail.hostImap}
    auth: true
    sslEnable: true
    port: 995
    socketFactoryClass: javax.net.ssl.SSLSocketFactory
    connectiontimeout: 5000
    timeout: 5000